# Generated by Django 5.2.6 on 2025-10-24 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_local_instructors'),
        ('core', '0002_remove_course_detailed_description_and_more'),
    ]

    operations = [
    ]
