# Generated by Django 5.2.6 on 2025-10-24 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_course_detailed_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='buy_url',
            field=models.URLField(blank=True, default='#', help_text='URL for the Buy Now button', max_length=500, null=True),
        ),
    ]
