# Generated by Django 5.2.6 on 2025-10-27 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_course_overview_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='core.course')),
            ],
            options={
                'verbose_name': 'Course Skill',
                'verbose_name_plural': 'Course Skills',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CourseTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(help_text='Tool icon image', upload_to='course_tool_icons/')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='core.course')),
            ],
            options={
                'verbose_name': 'Course Tool',
                'verbose_name_plural': 'Course Tools',
                'ordering': ['order'],
            },
        ),
    ]
