# Generated by Django 5.2.7 on 2025-10-27 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_courseskill_coursetool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetool',
            name='icon',
            field=models.ImageField(blank=True, help_text='Tool icon image', null=True, upload_to='course_tool_icons/'),
        ),
    ]
