# Generated by Django 5.2.7 on 2025-10-27 04:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20251027_0939'),
    ]

    operations = [
        migrations.RunSQL(
            "DROP TABLE IF EXISTS core_courseskill;",
            reverse_sql="",
        ),
        migrations.CreateModel(
            name='CourseSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='skills', to='core.course')),
            ],
            options={
                'verbose_name': 'Course Skill',
                'verbose_name_plural': 'Course Skills',
                'ordering': ['order'],
            },
        ),
    ]
