# Generated by Django 5.2.7 on 2025-10-27 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20251027_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseskill',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='CourseBrochure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Course Curriculum', max_length=200)),
                ('brochure_file', models.FileField(help_text='PDF file for the course brochure', upload_to='course_brochures/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brochures', to='core.course')),
            ],
            options={
                'verbose_name': 'Course Brochure',
                'verbose_name_plural': 'Course Brochures',
            },
        ),
    ]
