# Generated by Django 5.2.7 on 2025-10-27 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_payment_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseScheduleDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Label for this day/section (e.g. "Day 01")', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_days', to='core.course')),
            ],
            options={
                'verbose_name': 'Course Schedule Day',
                'verbose_name_plural': 'Course Schedule Days',
                'ordering': ['course', 'order'],
            },
        ),
        migrations.CreateModel(
            name='CourseScheduleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, help_text='Optional icon class (e.g. fa fa-video) or text', max_length=100, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.coursescheduleday')),
            ],
            options={
                'verbose_name': 'Course Schedule Item',
                'verbose_name_plural': 'Course Schedule Items',
                'ordering': ['day', 'order'],
            },
        ),
    ]
