# Generated by Django 5.2.6 on 2025-10-27 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_coursescheduleday_coursescheduleitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursescheduleitem',
            name='duration',
            field=models.CharField(blank=True, help_text='Video duration (e.g. 12:34)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='coursescheduleitem',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Thumbnail image for the video', null=True, upload_to='course_video_thumbs/'),
        ),
        migrations.AddField(
            model_name='coursescheduleitem',
            name='video_file',
            field=models.FileField(blank=True, help_text='Optional uploaded video file', null=True, upload_to='course_videos/'),
        ),
        migrations.AddField(
            model_name='coursescheduleitem',
            name='video_url',
            field=models.URLField(blank=True, help_text='External video URL (YouTube/Vimeo)', null=True),
        ),
    ]
