# Generated by Django 5.2.6 on 2025-10-28 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_add_progress_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AlterField(
            model_name='courseprogress',
            name='course_access',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='_progress', to='core.courseaccess'),
        ),
    ]
