# Generated by Django 5.2.7 on 2025-10-28 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_certificate_pdf_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyPurchaseSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_color', models.CharField(default='#ffffff', help_text='Card background color (hex)', max_length=50)),
                ('text_color', models.CharField(default='#333333', help_text='Card text color (hex)', max_length=50)),
                ('button_background', models.CharField(default='#28a745', help_text='Button background color (hex)', max_length=50)),
                ('button_text_color', models.CharField(default='#ffffff', help_text='Button text color (hex)', max_length=50)),
                ('button_text', models.CharField(default='Start Learning', help_text='Text for the button', max_length=50)),
                ('card_shadow', models.CharField(default='0 4px 6px rgba(0, 0, 0, 0.1)', help_text='CSS box-shadow value', max_length=100)),
                ('border_radius', models.CharField(default='15px', help_text='Card border radius', max_length=20)),
                ('progress_bar_color', models.CharField(default='#28a745', help_text='Progress bar color (hex)', max_length=50)),
                ('default_image', models.ImageField(blank=True, help_text='Default image for courses without their own image', null=True, upload_to='course_placeholder/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'My Purchase Page Settings',
                'verbose_name_plural': 'My Purchase Page Settings',
            },
        ),
    ]
