# Generated by Django 5.2.7 on 2025-10-28 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_mypurchasesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePurchaseCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_image', models.ImageField(help_text='Image shown on the course card', upload_to='course_purchase_cards/')),
                ('title', models.CharField(help_text='Course title shown on the card', max_length=200)),
                ('description', models.TextField(help_text='Short description shown on the card')),
                ('button_text', models.CharField(default='Start Learning', help_text='Text shown on the button', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_card', to='core.course')),
            ],
            options={
                'verbose_name': 'Course Purchase Card',
                'verbose_name_plural': 'Course Purchase Cards',
            },
        ),
        migrations.DeleteModel(
            name='MyPurchaseSettings',
        ),
    ]
