# Generated by Django 5.2.7 on 2025-10-28 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_add_course_purchase_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrochureDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('brochure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='core.coursebrochure')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brochure_downloads', to='core.course')),
            ],
            options={
                'verbose_name': 'Brochure Download',
                'verbose_name_plural': 'Brochure Downloads',
                'ordering': ['-downloaded_at'],
            },
        ),
    ]
