# Generated by Django 5.2.6 on 2025-11-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_examattempt_duration_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseexam',
            name='question_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of questions per attempt (0 = use all active questions)'),
        ),
    ]
