# Generated by Django 5.2.8 on 2025-11-24 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_courseexam_question_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='course_name',
            field=models.CharField(blank=True, help_text='Course name for certificate', max_length=255),
        ),
        migrations.AddField(
            model_name='certificate',
            name='score_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Score achieved on the exam', max_digits=5, null=True),
        ),
    ]
