# Generated by Django 5.2.8 on 2025-11-28 05:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_certificate_course_name_certificate_score_percentage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='course_name',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='score_percentage',
        ),
        migrations.CreateModel(
            name='ExamCertificateRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('contact', models.CharField(blank=True, max_length=50)),
                ('score_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('purchase_date', models.DateTimeField(blank=True, null=True)),
                ('joined_date', models.DateTimeField(blank=True, null=True)),
                ('course_duration_days', models.IntegerField(blank=True, null=True)),
                ('course_duration_months', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('violations', models.TextField(blank=True, help_text='Summary of exam violations, if any', null=True)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='certificates_uploaded/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_record', to='core.examattempt')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course')),
                ('course_access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.courseaccess')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_cert_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exam Certificate Record',
                'verbose_name_plural': 'Exam Certificate Records',
                'ordering': ['-created_at'],
            },
        ),
    ]
