# Generated by Django 5.2.6 on 2025-11-28 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_certificate_course_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(help_text='Student full name', max_length=200)),
                ('student_email', models.EmailField(help_text='Student email address', max_length=254)),
                ('student_phone', models.CharField(blank=True, help_text='Student contact number', max_length=20, null=True)),
                ('course_name', models.CharField(help_text='Course name', max_length=200)),
                ('course_duration_days', models.IntegerField(help_text='Total course duration in days')),
                ('course_duration_months', models.DecimalField(decimal_places=2, help_text='Course duration converted to months', max_digits=5)),
                ('purchased_date', models.DateTimeField(help_text='Date when student enrolled/purchased the course')),
                ('joined_date', models.DateTimeField(help_text='Date when student joined/enrolled')),
                ('exam_score_percentage', models.DecimalField(decimal_places=2, help_text='Exam score percentage (80% or above)', max_digits=5)),
                ('correct_answers', models.IntegerField(help_text='Number of correct answers')),
                ('total_questions', models.IntegerField(help_text='Total questions in exam')),
                ('exam_duration_taken_minutes', models.IntegerField(help_text='Time taken to complete exam in minutes')),
                ('exam_submitted_date', models.DateTimeField(help_text='Date and time of exam submission')),
                ('has_violations', models.BooleanField(default=False, help_text='Whether any violations were detected')),
                ('violation_count', models.IntegerField(default=0, help_text='Total number of violations recorded')),
                ('violation_details', models.TextField(blank=True, help_text='Details of violations in JSON format', null=True)),
                ('certificate_file', models.FileField(blank=True, help_text='Uploaded certificate file (PDF/Image)', null=True, upload_to='exam_certificates/%Y/%m/%d/')),
                ('certificate_uploaded_date', models.DateTimeField(blank=True, help_text='Date certificate was uploaded', null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes or comments', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this certificate is active/valid')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam_attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='core.examattempt')),
            ],
            options={
                'verbose_name': 'Exam Certificate',
                'verbose_name_plural': 'Exam Certificates',
                'ordering': ['-exam_submitted_date'],
            },
        ),
        migrations.DeleteModel(
            name='ExamCertificateRecord',
        ),
        migrations.AddIndex(
            model_name='examcertificate',
            index=models.Index(fields=['student_email'], name='core_examce_student_f89ef6_idx'),
        ),
        migrations.AddIndex(
            model_name='examcertificate',
            index=models.Index(fields=['is_active'], name='core_examce_is_acti_9b790d_idx'),
        ),
        migrations.AddIndex(
            model_name='examcertificate',
            index=models.Index(fields=['-exam_submitted_date'], name='core_examce_exam_su_b4433e_idx'),
        ),
    ]
